<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.example</groupId>
        <artifactId>platform</artifactId>
        <version>1.2</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>qt</artifactId>

    <properties>
        <!-- TEST DEPENDENCIES VERSION -->
        <junit.platfrom.version>1.10.2</junit.platfrom.version>
        <cucumber.version>7.18.1</cucumber.version>

        <!-- PROFILE SETTINGS -->
        <platform.args>--enable-native-access=ALL-UNNAMED</platform.args>
        <platform.headless.args></platform.headless.args>
        <platform.appName>QT_Demo</platform.appName>
        <platform.mainJar>${project.artifactId}-${project.version}.jar</platform.mainJar>
        <platform.mainClass>org.example.demo.QtMain</platform.mainClass>

        <!-- PLUGINS VERSIONS -->
        <helper.plugin.version>3.6.1</helper.plugin.version>
        <antrun.plugin.version>3.1.0</antrun.plugin.version>

        <!-- BUILD PROPERTIES -->
        <jextract.bin>${jextract.home}/bin/jextract</jextract.bin>
        <jextract.input>${project.basedir}/src/main/c++/src/</jextract.input>
        <jextract.output>${project.basedir}/src/generated/java</jextract.output>
        <jextract.target>org.example.demo.qt.port.ui.bridge</jextract.target>
        <jextract.name>UiBridgeConstants</jextract.name>
        <jextract.header>${project.basedir}/src/main/c++/src/ui/extract.h</jextract.header>
    </properties>

    <dependencies>
        <!-- MODULES -->
        <dependency>
            <groupId>org.example</groupId>
            <artifactId>model</artifactId>
        </dependency>
        <dependency>
            <groupId>org.example</groupId>
            <artifactId>core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.example</groupId>
            <artifactId>core</artifactId>
            <version>${project.version}</version>
            <type>test-jar</type>
            <scope>test</scope>
            <classifier>tests</classifier>
        </dependency>
        <dependency>
            <groupId>org.example</groupId>
            <artifactId>realization</artifactId>
        </dependency>
        <dependency>
            <groupId>org.example</groupId>
            <artifactId>realization</artifactId>
            <version>${project.version}</version>
            <type>test-jar</type>
            <scope>test</scope>
            <classifier>tests</classifier>
        </dependency>

        <!-- DI -->
        <dependency>
            <groupId>com.google.inject</groupId>
            <artifactId>guice</artifactId>
        </dependency>

        <!-- UTIL -->
        <dependency>
            <groupId>it.unimi.dsi</groupId>
            <artifactId>fastutil</artifactId>
            <version>8.5.18</version>
        </dependency>

        <!-- LOGGING -->
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
        </dependency>

        <!-- CODE GENERATION -->
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>

        <!-- TESTS -->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-junit-jupiter</artifactId>
        </dependency>
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-java</artifactId>
        </dependency>
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-junit-platform-engine</artifactId>
        </dependency>
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-guice</artifactId>
        </dependency>
        <dependency>
            <groupId>org.junit.platform</groupId>
            <artifactId>junit-platform-suite</artifactId>
        </dependency>
    </dependencies>

    <profiles>
        <profile>
            <id>qt-windows</id>
            <activation>
                <os><family>windows</family></os>
            </activation>
            <properties>
                <jextract.exec>cmd</jextract.exec>
                <jextract.arg>/c</jextract.arg>
                <os.preset>windows-msvc</os.preset>
                <stage.folder>Debug</stage.folder>
            </properties>
        </profile>
        <profile>
            <id>qt-linux</id>
            <activation>
                <os><family>unix</family></os>
            </activation>
            <properties>
                <jextract.exec>sh</jextract.exec>
                <jextract.arg>-c</jextract.arg>
                <os.preset>linux-gcc</os.preset>
                <stage.folder></stage.folder>
            </properties>
        </profile>
    </profiles>

    <build>
        <!-- Excluding qt resource from maven.
        They managed by dedicated ant-run command later -->
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
            <resource>
                <directory>src/main/resources/native</directory>
                <filtering>false</filtering>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-clean-plugin</artifactId>
                <configuration>
                    <filesets>
                        <fileset>
                            <directory>src/main/c++/build</directory>
                        </fileset>
                        <fileset>
                            <directory>src/generated/java</directory>
                        </fileset>
                    </filesets>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-failsafe-plugin</artifactId>
                <executions>
                    <execution>
                        <id>functional-tests</id>
                        <goals>
                            <goal>integration-test</goal>
                            <goal>verify</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <executions>
                    <execution>
                        <id>share-tests</id>
                        <phase>generate-test-sources</phase>
                        <goals>
                            <goal>unpack</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-enforcer-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>enforce</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <executions>
                    <!-- Fat JAR (All Dependencies) -->
                    <execution>
                        <id>fat</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
<!--                            <shadedArtifactAttached>true</shadedArtifactAttached>
                            <shadedClassifierName>raw</shadedClassifierName>-->
                            <finalName>qt-java-runtime</finalName>
                            <filters>
                                <filter>
                                    <!-- Security: Remove signature files from dependencies to avoid SecurityException -->
                                    <artifact>*:*</artifact>
                                    <excludes>
                                        <exclude>META-INF/*.SF</exclude>
                                        <exclude>META-INF/*.DSA</exclude>
                                        <exclude>META-INF/*.RSA</exclude>
                                        <exclude>module-info.class</exclude> <!-- Avoid JPMS conflicts in fat JARs -->
                                    </excludes>
                                </filter>
                            </filters>
                            <transformers>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                    <mainClass>${platform.mainClass}</mainClass>
                                </transformer>
                            </transformers>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-antrun-plugin</artifactId>
                <version>${antrun.plugin.version}</version>
                <executions>
                    <execution>
                        <id>jextract</id>
                        <phase>generate-sources</phase>
                        <goals><goal>run</goal></goals>
                        <configuration>
                            <target>
                                <exec executable="${jextract.exec}" failonerror="true">
                                    <arg value="${jextract.arg}" />`
                                    <arg value="${jextract.bin} --source -I ${jextract.input} --output ${jextract.output} --target-package ${jextract.target} --header-class-name ${jextract.name} ${jextract.header}" />
                                </exec>
                            </target>
                        </configuration>
                    </execution>
                    <execution>
                        <id>configure-qt</id>
                        <phase>verify</phase>
                        <goals><goal>run</goal></goals>
                        <configuration>
                            <target>
                                <exec executable="${jextract.exec}" dir="${project.basedir}/src/main/c++/" failonerror="true">
                                    <arg value="${jextract.arg}"/>
                                    <arg value="cmake -S . -B ${project.build.directory}/native/build -DNATIVE_RESOURCES_DIR=${project.basedir}/src/main/resources/native --preset ${os.preset} -DCMAKE_PREFIX_PATH=${qt.compiler}"/>
                                </exec>
                            </target>
                        </configuration>
                    </execution>
                    <execution>
                        <id>build-qt</id>
                        <phase>verify</phase>
                        <goals><goal>run</goal></goals>
                        <configuration>
                            <target>
                                <exec executable="${jextract.exec}" dir="${project.build.directory}/native/" failonerror="true">
                                    <arg value="${jextract.arg}"/>
                                    <arg value="cmake --build build"/>
                                </exec>
                            </target>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <artifactId>maven-resources-plugin</artifactId>
                <executions>
                    <execution>
                        <id>copy-qt-jar</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>copy-resources</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>
                                ${project.build.directory}/native/build/${stage.folder}
                            </outputDirectory>
                            <resources>
                                <resource>
                                    <directory>${project.build.directory}</directory>
                                    <includes>
                                        <include>qt-java-runtime.jar</include>
                                    </includes>
                                </resource>
                            </resources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
                <version>${helper.plugin.version}</version>
                <executions>
                    <execution>
                        <id>add-generated-sources</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>add-source</goal>
                        </goals>
                        <configuration>
                            <sources>
                                <source>src/generated/java</source>
                            </sources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
